### PR TITLE
Pass-through arbitrary param objects. Used for Babel's languageMap.

### PR DESCRIPTION
**Pull request by stephanebisson**

### CODE REVIEW

**Comment by nyurik** [comment]
Keys are not ordered in JavaScript, so you cannot assume the first one is the one to examine. https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by stephanebisson** [comment]
That's right. I don't think it had any impact based on how it was used but I have reworked it to be more clear and more aligned with what the function comment says it does.

**Comment by nyurik** [comment]
I see. Question is - should we silently ignore when objects are being used as parameters in a config? In other words, is there a need for objects as parameters?  I have not seen a use case yet, and it might get confusing - hence it was failing with multiple values.  I don't think we should silently ignore it just in case it will be used later on - people might get confused why something is not throwing an error but not working correctly.  Also, this PR would conflict with the other PR currently pending - the one that adds linting by @mooeypoo

**Comment by stephanebisson** [comment]
The use case is Babel's languageMap as illustrated [here](https://github.com/kartotherian/babel/blob/master/README.md)

I'm not sure what you mean by "silently ignore". What I'm proposing here is to still respect the special handling of "ref", "var", etc but allow a different object to pass through without being actively blocked by an exception.

Are you suggesting we should recurse in all objects and try to resolve "ref", "var", etc?

Another option altogether is to not support Babel's languageMap as an object literal. It is slightly more convenient than a file during testing or for a super-small setup but it is really not essential.

**Comment by nyurik** [comment]
Ah, sorry, yes, makes sense.  I think I used to have a URL serialization (when all params are converted back into a single url string), but I think it's gone now, so shouldn't be an issue.  Could you rebase your change on top of https://github.com/kartotherian/core/pull/5 ?

**Comment by nyurik** [comment]
thx, i will address linting in a bit

**Pull request merged**
